module:
  server: true
  client: true



# https://goframe.org/docs/web/server-config-file-template
server:
  address:     "51888"
#  openapiPath: "/api.json"
#  swaggerPath: "/swagger"
  dumpRouterMap: false
  graceful: true

# https://goframe.org/docs/core/glog-config
logger:
  level : "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"

redis:
  default:
    address: "ay.cname.com:6379"
    db: 15
    pass: "12345678"
  cache:
    address: "ay.cname.com:6379"
    db: 15
    pass: "12345678"

p2p:
  list:
#    - host: "192.168.50.173"
#      port: 51888
#      ssl: false
#      ws: ws
    - host: "ay.cname.com"
      port: 51888
      ssl: false
      ws: ws


