// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package p2p

import (
	"github.com/ayflying/p2p/api/p2p"
)

type ControllerV1 struct{}

func NewV1() p2p.IP2PV1 {
	return &ControllerV1{}
}
