
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  build:
    name: "p2p"
    arch: "amd64"
    system: "windows,linux"
    mod: "none"
    packSrc: "resource,manifest"
    version: "v1.0.0"
    #   output: "./bin/"
    #    cgo: true
    extra: -trimpath -ldflags="-s -w"
    dumpEnv: true
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        descriptionTag: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app